name: Deploy to GCP VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy Dockerized Flask App on GCP
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          docker stop flask-container || true
          docker rm flask-container || true
          docker pull YOUR_DOCKER_USERNAME/flask-cicd-api:latest
          docker run -d -p 8080:8080 --name flask-container bhavani789/flask-cicd-api:latest
        EOF
