name: CI/CD Deploy to GCP VM

on:
  push:
    branches:
      - main   # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Start SSH agent and add private key
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.NEW_PRIVATE_SSH_KEY }}

    - name: Run deployment script on VM
      run: |
        ssh -o StrictHostKeyChecking=no vkbhavani8@35.184.174.82 << 'EOF'
          cd /home/priya/flask-cicd-api
          git pull origin main
          # Add any other deployment commands here like docker build/run

    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.NEW_SSH_PRIVATE_KEY }}

    - name: Deploy to GCP VM
      run: |
        ssh -o StrictHostKeyChecking=no vkbhavani8@35.184.174.82 << EOF
          cd /home/vkbhavani8/flask-cicd-api || exit 1
          git pull origin main
          docker build -t flask-cicd-api:latest .
          docker stop flask-container || true
          docker rm flask-container || true
          docker run -d -p 8080:8080 --name flask-container flask-cicd-api:latest
 31d4562 (Save local changes before pull)
          exit
        EOF
 
